import React, { useState } from 'react';
import { Link, useParams, useSearchParams } from 'react-router-dom';
import { Search, Check, ArrowRight, Heart, ShieldCheck } from 'lucide-react';
import { services, articles, faqs, suburbs, legal, phone } from './data';
import { PageHero, Eyebrow, Button, TextLink, Icon, Asset, SectionHeading, ServiceGrid, StartSteps, FundingCards, FAQList, FinalCTA, ResourceCards } from './components';
import ServiceAreaMap from './ServiceAreaMap';

export function ServicesPage() {
  return <><PageHero eyebrow="Our services" title="Support for your" accent="everyday."><p>At home, out in the community, and through life’s changes. Six services, shaped around you.</p><Button>Find your support</Button></PageHero><section className="section"><div className="container"><ServiceGrid /><figure className="service-panorama"><Asset name="services" alt="Illustration bringing together household help, community support, transport, planning and nursing." sizes="(max-width: 700px) 100vw, 1120px" /><figcaption>Everyday support, connected. Illustrative scenes, not actual participants or service locations.</figcaption></figure></div></section><StartSteps /><section className="section funding-section"><div className="container"><SectionHeading eyebrow="Funding pathways" title="Let’s make the next step" accent="clearer." /><FundingCards /></div></section><FinalCTA /></>;
}

export function ServicePage() {
  const { slug } = useParams();
  const service = services.find(item => item.slug === slug);
  if (!service) return <NotFound />;
  return <><PageHero eyebrow={service.title} title={service.title === 'Cleaning' ? 'A fresh home.' : service.title === 'Nursing' ? 'Qualified care.' : service.title} accent={service.title === 'Cleaning' ? 'A lighter day.' : service.title === 'Nursing' ? 'Close to home.' : 'On your terms.'} breadcrumb={['/services', 'Services']}><p>{service.intro}</p><Button to={`/contact?service=${service.slug}`}>Ask about {service.title.toLowerCase()}</Button></PageHero><section className="section"><div className="container detail-grid"><div className="detail-content"><Eyebrow>{service.label}</Eyebrow><h2>Help that fits <em>your life.</em></h2><p className="lead">{service.audience}</p><p>{service.detail}</p><h2>What we can help with</h2><ul className="inclusion-list">{service.includes.map(item => <li key={item}><Check size={20} aria-hidden="true" />{item}</li>)}</ul><div className="scope-note"><h3>Let’s agree on the details</h3><p>{service.limit}</p></div><h2>Shaped around your preferences</h2><p>We start by listening. Tell us about your routine, what works for you and the things you would like us to know. You can involve your family, carer or support coordinator. Your service agreement records the support you have chosen.</p><p>Workers are screened and supported by the OCD Brilliance team. Nursing is delivered by qualified Registered Nurses within an assessed care plan. The team confirms the right skills for your particular support.</p><h2>A few useful questions</h2><FAQList items={[[service.faq, service.answer], faqs[2], faqs[6]]} /></div><aside><div className="service-summary"><span className="service-icon"><Icon name={service.icon} size={35} /></span><h2>Your support, at a glance</h2><dl><div><dt>Funding</dt><dd>NDIS — subject to your plan</dd></div><div><dt>Plan management</dt><dd>Self, plan or agency managed</dd></div><div><dt>Where</dt><dd>Perth’s northern suburbs</dd></div><div><dt>Getting started</dt><dd>A conversation and an agreed plan</dd></div></dl><Button to={`/contact?service=${service.slug}`}>Talk with our team</Button><a className="phone-link" href="tel:0428820059">Or call {phone}</a><Link to="/funding">Explore funding options</Link><Link to="/areas-we-serve">Check your area</Link></div><div className="sidebar-note"><Icon name="shield" /><h3>Clear from the start.</h3><p>Ask about costs, travel and cancellation terms before agreeing to support.</p><TextLink to="/participant-rights">Know your rights</TextLink></div></aside></div></section><StartSteps /><section className="section"><div className="container"><SectionHeading eyebrow="Connected support" title="You might also" accent="find helpful." /><ServiceGrid list={services.filter(item => item.slug !== slug).slice(0, 3)} /></div></section><FinalCTA /></>;
}

export function FundingPage() {
  return <><PageHero eyebrow="Funding your support" title="A little clarity." accent="A better next step."><p>You don’t need to have every answer. We’ll talk through your funding and confirm what support is available for you.</p></PageHero><section className="section"><div className="container"><FundingCards /><div className="editorial-two" id="ndis"><div><Eyebrow>National Disability Insurance Scheme</Eyebrow><h2>Your plan.<br /><em>Your possibilities.</em></h2><p>OCD Brilliance is listed on its source website as a registered NDIS provider, supporting the three plan-management arrangements below.</p><p>Support must fit your plan and agreed needs. Your first conversation is an opportunity to clarify services, rates, travel and availability.</p><Button>Let’s talk about your plan</Button></div><div className="numbered-list">{[['Self-managed', 'You manage your NDIS funding and arrange payment for your supports. Discuss invoices and service agreements with the team.'], ['Plan-managed', 'Your plan manager handles payments. The team can discuss the invoicing arrangements you need.'], ['Agency-managed', 'The NDIA manages your plan payments. Registered providers can work with this arrangement, subject to the supports in your plan.']].map(([title, text], index) => <div key={title}><span>0{index + 1}</span><div><h3>{title}</h3><p>{text}</p></div></div>)}</div></div><div className="scope-note"><h2>DVA and aged care: what “coming soon” means</h2><p>The source website describes these pathways as expanding. Its FAQ says OCD Brilliance is not yet delivering services under DVA or Commonwealth aged care. The team can provide the latest update; this presentation does not accept bookings under those pathways.</p></div></div></section><section className="section sage-section"><div className="container narrow"><SectionHeading eyebrow="Clear expectations" title="Before you" accent="get started." /><ul className="inclusion-list">{['Confirm the support is suitable and fits your funding.', 'Ask for a clear explanation of rates and any travel charges.', 'Read your individual service agreement, including cancellation terms.', 'Ask questions or involve your support coordinator before you agree.'].map(text => <li key={text}><Check size={20} aria-hidden="true" />{text}</li>)}</ul><TextLink to="/participant-rights">Your choice and your rights</TextLink></div></section><FinalCTA /></>;
}

export function AboutPage() {
  return <><PageHero eyebrow="Our story" title="A family business." accent="A personal commitment."><p>Built on the belief that good support starts with noticing the person, not just the task.</p></PageHero><section className="section"><div className="container about-grid"><figure className="owners-photo"><img src="/assets/landing/owners.webp" width="800" height="900" alt="Adriana and Felician Giuca, owners of OCD Brilliance." loading="lazy" /><figcaption>Adriana & Felician Giuca · Owners, OCD Brilliance</figcaption></figure><div><Eyebrow>The people behind the care</Eyebrow><h2>A heart that understands.<br /><em>Eyes that notice.</em></h2><p className="lead">For Adriana and Felician Giuca, it starts with doing right by the person in front of them.</p><p>Their experience in the cleaning industry gave them a window into everyday life at home: the routines, the challenges and the difference that reliable help can make.</p><p>In 2023, they acquired OCD Brilliance, a business founded in 2018. Building on that foundation, they expanded into disability support, bringing the same attention to detail to a broader range of care.</p><p>Today, the family-owned Perth team offers six services, with the participant’s choices and comfort at the centre.</p><Button>Meet us in a conversation</Button></div></div></section><section className="section sage-section" id="standards"><div className="container"><SectionHeading eyebrow="What we stand for" title="Care is in" accent="the details." /><div className="values-grid">{[['heart', 'Respect for you', 'Your choices, routines and preferences shape the support.'], ['shield', 'Safety in the everyday', 'Workers are screened, trained and supported by the team.'], ['users', 'Familiar relationships', 'Careful matching and clear communication around worker changes.'], ['compass', 'Honest conversations', 'Agreed services and itemised billing, with questions always welcome.'], ['leaf', 'Care for your home', 'A considered cleaning method and attention to product sensitivities.'], ['pin', 'Local connection', 'A family business serving communities across Perth’s north.']].map(([icon, title, text]) => <article key={title}><Icon name={icon} size={30} /><h3>{title}</h3><p>{text}</p></article>)}</div><div className="source-note">The source website states OCD Brilliance is NDIS registered and audited. Ask the team for current registration and the scope relevant to your support.</div></div></section><section className="section"><div className="container split-banner"><div><Eyebrow>Make a difference, every day</Eyebrow><h2>There’s a person<br /><em>behind every visit.</em></h2><p>If thoughtful, dependable care sounds like you, explore the team’s roles.</p><TextLink to="/careers">Find your place on the team</TextLink></div><Asset name="texture" alt="" /></div></section><FinalCTA /></>;
}

export function AreasPage() {
  const [query, setQuery] = useState('');
  const results = suburbs.filter(suburb => suburb.toLowerCase().includes(query.toLowerCase().trim()));
  return <>
    <PageHero eyebrow="Areas we serve" title="Local people." accent="Familiar places."><p>Supporting participants north of the river, across Perth’s northern suburbs and surrounding communities.</p></PageHero>
    <section className="section"><div className="container">
      <div className="areas-top"><div><Eyebrow>Close to home</Eyebrow><h2>Find your <em>neighbourhood.</em></h2><p>Explore the listed areas across Perth’s north, from Yanchep and Alkimos to Midland and Greenmount. Search a suburb to find its place on the map. Service and worker availability should be confirmed with the team.</p></div><ServiceAreaMap query={query} onQueryChange={setQuery} /></div>
      <p className="results-count" role="status">{results.length} {results.length === 1 ? 'suburb' : 'suburbs'} found</p>
      {results.length ? <ul className="area-list">{results.map(suburb => <li key={suburb}><span className="area-dot" aria-hidden="true" />{suburb}</li>)}</ul> : <div className="empty-state"><h2>Let’s check with the team.</h2><p>No listed suburb matches “{query}”. That doesn’t necessarily mean we can’t help.</p><button className="button button-secondary" onClick={() => setQuery('')}>Clear search</button><TextLink to="/contact">Ask about your location</TextLink></div>}
      <div className="scope-note"><h2>Don’t see your suburb?</h2><p>Call <a href="tel:0428820059">{phone}</a> or send an enquiry. The team can confirm your location and the support you’re considering.</p></div>
    </div></section><FinalCTA />
  </>;
}

export function ResourcesPage() {
  const [params, setParams] = useSearchParams();
  const query = params.get('q') || '';
  const category = params.get('category') || 'All';
  const categories = ['All', ...new Set(articles.map(article => article.category))];
  const results = articles.filter(article => (category === 'All' || article.category === category) && `${article.title} ${article.excerpt}`.toLowerCase().includes(query.toLowerCase()));
  const filter = (key, value) => setParams(previous => { const next = new URLSearchParams(previous); value && value !== 'All' ? next.set(key, value) : next.delete(key); return next; }, { replace: true });
  return <><PageHero eyebrow="The everyday journal" title="A little clarity" accent="goes a long way."><p>Practical reads, honest conversations and insights into everyday support, from the OCD Brilliance source archive.</p></PageHero><section className="section"><div className="container"><div className="resource-filters"><div className="search-field"><label htmlFor="resource-search">Find an article</label><div><Search size={20} aria-hidden="true" /><input id="resource-search" type="search" placeholder="Search guides and insights" value={query} onChange={event => filter('q', event.target.value)} /></div></div><div className="field"><label htmlFor="category">Browse a topic</label><select id="category" value={category} onChange={event => filter('category', event.target.value)}>{categories.map(item => <option key={item}>{item}</option>)}</select></div></div><p className="archive-notice">Source archive. Funding rules, pricing and registration guidance can change. Check current official information before relying on an article.</p><p role="status" className="results-count">{results.length} {results.length === 1 ? 'article' : 'articles'}</p>{results.length ? <ResourceCards list={results} /> : <div className="empty-state"><Search size={32} aria-hidden="true" /><h2>No matching reads, yet.</h2><p>Try a broader word or explore all topics.</p><button className="button" onClick={() => setParams({})}>Clear filters <ArrowRight size={18} aria-hidden="true" /></button></div>}</div></section><FinalCTA /></>;
}

export function ArticlePage() {
  const { slug } = useParams();
  const article = articles.find(item => item.slug === slug);
  if (!article) return <NotFound />;
  return <><PageHero eyebrow={article.category} title={article.title} breadcrumb={['/resources', 'Resources']}><p className="article-byline">{article.sourceDate || 'Source article · OCD Brilliance'} · {article.readingMinutes} minute reading estimate</p></PageHero><section className="section"><div className="container article-layout"><aside className="article-sidebar"><Eyebrow>In the source archive</Eyebrow><p>This article is preserved from the source website for this presentation. Dates, rates and policy statements are not independently verified here.</p><p>For current guidance, check <a href="https://www.ndis.gov.au/" target="_blank" rel="noreferrer">the NDIS</a> and <a href="https://www.ndiscommission.gov.au/" target="_blank" rel="noreferrer">the NDIS Commission</a>.</p><a className="text-link" href={`https://ocdbrilliance.com.au/#${article.id}`} target="_blank" rel="noreferrer">View original article <ArrowRight size={17} aria-hidden="true" /></a><TextLink to="/resources">All resources</TextLink></aside><article className="prose source-article" dangerouslySetInnerHTML={{ __html: article.html }} /></div></section><section className="section sage-section"><div className="container"><SectionHeading eyebrow="Keep exploring" title="A few more" accent="helpful reads." /><ResourceCards list={articles.filter(item => item.slug !== slug).slice(0, 3)} /></div></section><FinalCTA /></>;
}

export function CareersPage() {
  const roles = [['Cleaner', 'Casual / part-time', 'NDIS Worker Screening required'], ['Support Worker', 'Casual / part-time', 'Own vehicle and comprehensive insurance required'], ['Support Coordinator', 'Perth metro', 'Disability or allied health background required'], ['Registered Nurse', 'ABN contractor', 'AHPRA registration required']];
  return <><PageHero eyebrow="Join the team" title="Bring your care" accent="to work."><p>Small moments can make a big difference. Join a Perth team that values thoughtful, dependable people.</p><Button to="/contact?purpose=careers">Start a careers conversation</Button></PageHero><section className="section"><div className="container"><div className="career-intro"><div><Eyebrow>A workplace with purpose</Eyebrow><h2>Good people.<br /><em>Meaningful work.</em></h2></div><p>OCD Brilliance describes a workplace with flexible hours, induction training, ongoing development and an office team you can talk to. Bring your skills and your attention to the person behind every task.</p></div><div className="career-perks">{[['heart', 'Work that matters'], ['users', 'A supportive team'], ['compass', 'Space to learn'], ['clock', 'Flexible hours']].map(([icon, title]) => <div key={title}><Icon name={icon} /><h3>{title}</h3></div>)}</div><SectionHeading eyebrow="Roles on the source website" title="Find your" accent="place." /><p className="archive-notice">These roles are listed on the original website. Confirm current vacancies directly with the team.</p><div className="jobs">{roles.map(([role, type, requirement]) => <article key={role}><div><h3>{role}</h3><p>Perth · {type}</p><span>{requirement}</span></div><Button to={`/contact?purpose=careers&role=${encodeURIComponent(role)}`} secondary>Enquire about role</Button></article>)}</div><div className="scope-note"><h2>What happens next?</h2><p>Start a conversation about your experience and the role you’re interested in. The live source website invites a résumé and a brief introduction; this local presentation does not accept files or send applications.</p></div></div></section><FinalCTA /></>;
}

export function FAQPage() { return <><PageHero eyebrow="Your questions" title="Good questions." accent="Clear answers."><p>From your first enquiry to your regular support, here are a few things you may be wondering.</p></PageHero><section className="section"><div className="container narrow"><FAQList /><div className="scope-note"><h2>Let’s talk about your question.</h2><p>No two people need exactly the same support. The team can discuss your circumstances.</p><Button>Talk with our team</Button></div></div></section><FinalCTA /></>; }

export function RightsPage() { return <><PageHero eyebrow="Participant rights" title="Your support." accent="Your choice."><p>You deserve care that respects your decisions, privacy, dignity and the way you want to live.</p></PageHero><section className="section"><div className="container narrow prose"><h2>You are part of every decision</h2><p>The source website sets out participants’ rights to make informed choices, involve people they trust, ask questions and raise concerns.</p><ul>{['Be treated with dignity and respect for your individual needs.', 'Make informed decisions about the supports and providers you choose.', 'Have your privacy respected and your information protected.', 'Receive support free from abuse, neglect, exploitation and violence.', 'Involve your family, carer, advocate or coordinator in decisions.', 'Raise a complaint without it affecting your support.', 'Discuss ending or changing an arrangement in line with your service agreement.', 'Receive culturally safe and inclusive support.'].map(right => <li key={right}>{right}</li>)}</ul><h2>Understand what you are agreeing to</h2><p>Before support starts, ask about the service, worker arrangements, costs, travel, cancellations and how to change your support. Take time to read your agreement, and ask for an explanation whenever something is unclear.</p><h2>Have someone in your corner</h2><p>You can involve someone you trust. If you want to raise a concern, the team and the NDIS Commission are available.</p><Button to="/complaints">Feedback & complaints</Button><p><Link to="/terms">Read the archived terms and conditions</Link></p></div></section><FinalCTA /></>; }

export function ComplaintsPage() { return <><PageHero eyebrow="Feedback & complaints" title="Your voice matters." accent="We’re here to listen."><p>A question, a concern, or something we could do better. You can speak up without it affecting your support.</p></PageHero><section className="section"><div className="container detail-grid"><div className="prose"><h2>Start wherever you feel comfortable</h2><p>You may contact OCD Brilliance directly or speak with the NDIS Quality and Safeguards Commission. You do not need to use this demonstration form.</p><ol className="complaint-steps"><li><h3>Talk with the team</h3><p>Call <a href="tel:0428820059">{phone}</a> or email <a href="mailto:admin@ocdbrilliance.com.au">admin@ocdbrilliance.com.au</a>. You can involve a family member, carer or advocate.</p></li><li><h3>Know what to expect</h3><p>The source terms say complaints are acknowledged within 2 business days, with an aim to resolve them within 10 business days. Contact the team to discuss the process.</p></li><li><h3>Independent help is available</h3><p>Contact the NDIS Commission on <a href="tel:1800035544">1800 035 544</a> or visit <a href="https://www.ndiscommission.gov.au/" target="_blank" rel="noreferrer">ndiscommission.gov.au</a>. For privacy matters, contact the <a href="https://www.oaic.gov.au/" target="_blank" rel="noreferrer">Office of the Australian Information Commissioner</a>.</p></li></ol><Button to="/contact?purpose=complaint">Preview feedback enquiry</Button></div><aside className="service-summary"><Icon name="heart" size={34} /><h2>You have a right to be heard.</h2><p>Raising a concern should never affect the quality of your support.</p><TextLink to="/participant-rights">Read your rights</TextLink><hr /><h3>Immediate danger?</h3><p>Call <a href="tel:000">000</a> in an emergency. This website is not an emergency service.</p></aside></div></section></>; }

export function LegalPage({ type }) { return <><PageHero eyebrow="Participant information" title={type === 'privacy' ? 'Privacy policy' : 'Terms & conditions'}><p>Source policy archive · {type === 'privacy' ? 'April 2026' : 'July 2026'}</p></PageHero><section className="section"><div className="container narrow"><div className="scope-note"><h2>About this presentation</h2><p>This local demo does not submit forms, store entries or load analytics. The policy below is archived from the original business website and describes that service, not a new service agreement.</p>{type === 'terms' && <p><strong>Cancellation clarification:</strong> the source FAQ and the terms below give different notice periods. Confirm the applicable terms in your individual service agreement with the team; this presentation does not determine fees.</p>}<a href={`https://ocdbrilliance.com.au/#pg-${type}`} target="_blank" rel="noreferrer">View the original policy</a></div><div className="prose legal-content" dangerouslySetInnerHTML={{ __html: legal[type] }} /></div></section></>; }

export function NotFound() { return <><PageHero eyebrow="Page not found" title="A little off track?" accent="Let’s find your way."><p>We couldn’t find that page. Your next step is still close by.</p><div className="hero-actions"><Button to="/">Back to home</Button><Button to="/services" secondary>Explore services</Button></div></PageHero><section className="section"><div className="container narrow"><h2>Looking for a conversation?</h2><p>The team can help with your question.</p><TextLink to="/contact">Get in touch</TextLink></div></section></>; }
